workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.2
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.checksfleet.app"
        APPLE_TEAM_ID: "P35Y6M742T"
    integrations:
      app_store_connect: checksfleet
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile_flutter/finality_app
          flutter pub get
      
      - name: Create .env file
        script: |
          cd mobile_flutter/finality_app
          cat > .env << EOF
          SUPABASE_URL=https://lqrulgkavtzummbsxsok.supabase.co
          SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcnVsZ2thdnR6dW1tYnN4c29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMTc5OTAsImV4cCI6MjA3NTY5Mzk5MH0.HyY4qR7OLsadOnwITmdn1tAiKyN7AVuNLcuVpLaQfKM
          EOF
          echo "✅ .env file created"

      - name: Install CocoaPods
        script: |
          cd mobile_flutter/finality_app/ios
          pod install

      - name: Remove alpha channel from app icons
        script: |
          ICON_DIR="mobile_flutter/finality_app/ios/Runner/Assets.xcassets/AppIcon.appiconset"
          for icon in "$ICON_DIR"/*.png; do
            # Convert PNG -> JPEG (strips alpha) -> PNG
            sips -s format jpeg "$icon" --out "${icon%.png}.jpg"
            sips -s format png "${icon%.png}.jpg" --out "$icon"
            rm -f "${icon%.png}.jpg"
          done
          echo "✅ Alpha channel removed from all app icons"

      - name: Set up code signing
        script: |
          keychain initialize
          
          # Generate a fresh RSA private key for certificate creation
          openssl genrsa -out /tmp/cert_private_key.pem 2048
          
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key=@file:/tmp/cert_private_key.pem
          
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          cd mobile_flutter/finality_app
          flutter build ipa --release \
            --build-name=3.8.1 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
          
          cp build/ios/ipa/*.ipa $CM_BUILD_DIR/ChecksFleet.ipa || true
          echo "Build complete"
          ls -lh $CM_BUILD_DIR/*.ipa || ls -lh build/ios/ipa/ || echo "IPA not found"

    artifacts:
      - ChecksFleet.ipa
      - mobile_flutter/finality_app/build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - mahdi.convoyages@gmail.com
        notify:
          success: true
          failure: true
        
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: 3.38.2
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile_flutter/finality_app
          flutter pub get
      
      - name: Create .env file
        script: |
          cd mobile_flutter/finality_app
          cat > .env << EOF
          SUPABASE_URL=https://lqrulgkavtzummbsxsok.supabase.co
          SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcnVsZ2thdnR6dW1tYnN4c29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMTc5OTAsImV4cCI6MjA3NTY5Mzk5MH0.HyY4qR7OLsadOnwITmdn1tAiKyN7AVuNLcuVpLaQfKM
          EOF
      
      - name: Build Android APK
        script: |
          cd mobile_flutter/finality_app
          flutter build apk --release
    
    artifacts:
      - mobile_flutter/finality_app/build/app/outputs/flutter-apk/app-release.apk
