workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.2
      xcode: latest
      cocoapods: default
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.checksfleet.app"
        APPLE_TEAM_ID: "P35Y6M742T"
    integrations:
      app_store_connect: checksfleet
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile_flutter/finality_app
          flutter pub get
      
      - name: Create .env file
        script: |
          cd mobile_flutter/finality_app
          cat > .env << EOF
          SUPABASE_URL=https://lqrulgkavtzummbsxsok.supabase.co
          SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcnVsZ2thdnR6dW1tYnN4c29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMTc5OTAsImV4cCI6MjA3NTY5Mzk5MH0.HyY4qR7OLsadOnwITmdn1tAiKyN7AVuNLcuVpLaQfKM
          EOF
          echo "✅ .env file created"

      - name: Install CocoaPods
        script: |
          cd mobile_flutter/finality_app/ios
          pod install

      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_STORE \
            --create
          keychain initialize
          app-store-connect certificates list \
            --type IOS_DISTRIBUTION \
            --certificate-key=@env:APP_STORE_CONNECT_PRIVATE_KEY \
            --issuer-id=$APP_STORE_CONNECT_ISSUER_ID \
            --key-id=$APP_STORE_CONNECT_KEY_IDENTIFIER || \
          app-store-connect certificates create \
            --type IOS_DISTRIBUTION \
            --certificate-key=@env:APP_STORE_CONNECT_PRIVATE_KEY \
            --issuer-id=$APP_STORE_CONNECT_ISSUER_ID \
            --key-id=$APP_STORE_CONNECT_KEY_IDENTIFIER
          keychain add-certificates
          xcode-project use-profiles \
            --project=mobile_flutter/finality_app/ios/Runner.xcodeproj

      - name: Build iOS IPA
        script: |
          cd mobile_flutter/finality_app
          flutter build ipa --release \
            --build-name=3.8.0 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
          
          cp build/ios/ipa/*.ipa $CM_BUILD_DIR/ChecksFleet.ipa || true
          echo "✅ IPA created"
          ls -lh $CM_BUILD_DIR/*.ipa || ls -lh build/ios/ipa/ || true

    artifacts:
      - ChecksFleet.ipa
      - mobile_flutter/finality_app/build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - mahdi.convoyages@gmail.com
        notify:
          success: true
          failure: true
        
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: 3.38.2
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile_flutter/finality_app
          flutter pub get
      
      - name: Create .env file
        script: |
          cd mobile_flutter/finality_app
          cat > .env << EOF
          SUPABASE_URL=https://lqrulgkavtzummbsxsok.supabase.co
          SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcnVsZ2thdnR6dW1tYnN4c29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMTc5OTAsImV4cCI6MjA3NTY5Mzk5MH0.HyY4qR7OLsadOnwITmdn1tAiKyN7AVuNLcuVpLaQfKM
          EOF
      
      - name: Build Android APK
        script: |
          cd mobile_flutter/finality_app
          flutter build apk --release
    
    artifacts:
      - mobile_flutter/finality_app/build/app/outputs/flutter-apk/app-release.apk
